### ISSUE TITLE
Cmake error at CMakelists.txt:68

### ISSUE THREAD

**Issue by brudolp** [shwsh/qshell#1]
Antergos(Arch), cmake error
extra-cmake-modules and plasma-meta are installed

git clone https://github.com/ffwff/qshell/
mkdir ~/qshell/build
cd ~/qshell/build
cmake ..

`-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5Config: /usr/lib64/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.54.0") 
-- Found KF5KIO: /usr/lib64/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.54.0") 
-- Found KF5WindowSystem: /usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.54.0") 
-- Found KF5: success (found suitable version "5.54.0", minimum required is "5.3.0") found components:  Config KIO WindowSystem 
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Configuring done
CMake Error at CMakeLists.txt:68 (add_executable):
  Cannot find source file:

    pamixer/callbacks.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:68 (add_executable):
  No SOURCES given to target: qshell

-- Build files have been written to: ~/qshell/build

`

**Comment by ffwff** [comment]
Check your `pamixer` directory, is it empty?

If so, you should try cloning the pamixer submodule using the command:

```
git submodule update --init --recursive
```

**Comment by ffwff** [comment]
**Note:** as of commit 6d6f6cc Q::Shell no longer uses pamixer as a dependency, so no recursive cloning is necessary.
