### ISSUE TITLE
i3 windows over qshell

### ISSUE THREAD

**Issue by Almamu** [shwsh/qshell#6]
(continuation of https://www.reddit.com/r/unixporn/comments/aotk1r/i3gapsqshell_tile_in_style/eg7xuvu/)
As the thread says I'm using i3 as window manager and qshell launched from SDDM (using the qshell session) on Arch Linux.
Unless I'm mistaken the windows should be inside the space between the widgets in qshell like is shown in the reddit post, but I get a very different situation. My windows place using most of the screen and hide the qshell widgets. I'm using the sora theme from the repository (just changed a couple of lines for it to use my custom actions):

If I enable AlwaysTop on the panels It just changes the way they are rendered but the windows still take the whole screen: https://imgur.com/AApNFvN

`i3 version 4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors`
I'm using a multimonitor configuration right now.

**Comment by ffwff** [comment]
Oh, I see what you're getting at now. Those gaps are outer window gaps which are handled by i3-gaps, not regular i3 or this shell.

**Comment by Almamu** [comment]
Oh, I that makes sense. I didn't think of that. I'll set up the gaps to make space for qshell then. Thank you!
