### ISSUE TITLE
Black screen when starting

### ISSUE THREAD

**Issue by alex47** [shwsh/qshell#8]
If I use `kquitapp plasmashell; sleep 2; qshell` I get a black screen with the following message:

![a](https://user-images.githubusercontent.com/10761683/52968825-bf667600-33ae-11e9-8080-1d8de0523802.png)

If I select qshell on the login screen it launches plasma instead.

**Comment by ffwff** [comment]
Can you try compiling the shell in debug mode by passing `-DCMAKE_BUILD_TYPE=DEBUG` to cmake and running it that way?

You should also try checking if `qshellrc` exists in your `~/.config` dir.

**Comment by alex47** [comment]
Compiled with `cmake -DCMAKE_BUILD_TYPE=DEBUG ..` but still no other output
I don't have `qshellrc` file in `~/.config`

![b](https://user-images.githubusercontent.com/10761683/53107408-3fb6e380-3535-11e9-869f-738e320cb739.png)

**Comment by ffwff** [comment]
Q::Shell requires a config file to work. You might want to copy-paste one of the themes (`qshellrc` and `qshell.css`) in the `themes` directory to `~/.config` and change the configuration a bit. There is a reference manual for the config file in the [wiki](https://github.com/ffwff/qshell/wiki/Config-reference).

**Comment by alex47** [comment]
ok that fixes it
it adds the panels but the screen is still almost purely black because it looks for a predetermined image as wallpaper and can't find it, but that's for another issue
this one is solved
